### PR TITLE
fix: running upgrade.sh should not duplicate domain name

### LINKED ISSUE #119: DOMAIN_NAME is duplicated on upgrade
```bash
bash <(curl -LsS https://raw.githubusercontent.com/supportpal/helpdesk-install/master/templates/docker-monolithic/setup.sh)
vim docker-compose.yml # change 4.1.2 to 4.1.0
docker compose up -d
docker compose exec supportpal /bin/bash /init/init-helpdesk.sh
bash <(curl -LsS https://raw.githubusercontent.com/supportpal/helpdesk-install/master/templates/docker-monolithic/upgrade.sh)
docker compose exec -u www-data supportpal bash -c "php artisan app:upgrade"
```

`.env`:
```
DOMAIN_NAME=ip-10-0-2-102
DOMAIN_NAME=
```

The blank `DOMAIN_NAME` breaks the auto generated `Caddyfile` and so caddy fails to start:
```
:80 {
  reverse_proxy 127.0.0.1:8080
}

 {
  reverse_proxy 127.0.0.1:8080
}
```

### PR DESCRIPTION
**Pull request by Gaitholabi**
fixes #119

### CODE REVIEW

File: templates/docker-monolithic/upgrade.sh [hunk 1]
```diff
@@ -60,13 +60,19 @@ update_volumes() {
...
+}
+
 update_env() {
-    grep  "hostname" docker-compose.override.yml | xargs | sed "s/hostname: /DOMAIN_NAME=/" >> .env
-    if [[ "$(uname -s)" == Darwin ]]; then
-        sed -i "" -e "s/hostname:.*/hostname: ''/" docker-compose.override.yml
-    else
-        sed -i -e "s/hostname:.*/hostname: ''/" docker-compose.override.yml
-    fi
+  if ! grep -qs 'DOMAIN_NAME' .env; then
```
Comment (bytestream) [inline templates/docker-monolithic/upgrade.sh:73]:
```suggestion
  if ! grep -qs 'DOMAIN_NAME=' .env; then
```

Probably more reliable?

**Review by bytestream — APPROVED** [review]
